[package]
name = "panoptes"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.147"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = { version = "1.0.136", features = ["derive"] }
